name: Develop Branch Tasks Workflow

# Trigger on push to main or develop branch
on:
  push:
    branches:
      - develop
      - main

jobs:
  # First job: Setup environment
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Step
        run: echo 'Job Setup: Preparing environment'

  # Second job: Run tasks, depends on setup
  run-tasks:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Step
        run: echo 'Job Run-Tasks: Running tasks because Setup succeeded'
